server:
  port: 4000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/springboot"
    username: jpauser
    password: jpauser